### ISSUE TITLE
CombineGVCFs: ERROR input alleles must contain <NON_REF>

### ISSUE THREAD

**Issue by pontikos** [vplagnol/pipelines#14] opened 2015-01-06 18:53 UTC
Running CombineGVCFs on files which were generated by HaplotypeCalller:

```sh
/share/apps/jdk1.7.0_45/jre/bin/java -Djava.io.tmpdir=/scratch2/vyp-scratch2/vincent/temp/novoalign -Xmx7g -jar /cluster/project8/vyp/vincent/Software/GenomeAnalysisTK-3.3-0/GenomeAnalysisTK.jar -T CombineGVCFs -R /scratch2/vyp-scratch2/reference_datasets/human_reference_sequence/human_g1k_v37.fasta -L 17 -o Project_Levine_January2015/CombineGVCFs/data/chr17.gvcf.gz --variant /cluster/project8/IBDAJE/jointgvcf/Macrogen_1/jointgvcf_chr17.vcf.gz --variant /cluster/project8/IBDAJE/jointgvcf/1410AHP-0004_ElenaSchiff_211samples/jointgvcf_chr17.vcf.gz  --variant /cluster/project8/IBDAJE/jointgvcf/1411AHP-0005_ElenaSchiff_75samples/jointgvcf_chr17.vcf.gz
```
generates the following error:

```
[rmhanpo@morecambe1:~/IBDAJE/jointgvcf/Project_Levine_January2015/CombineGVCFs]$ cat err/CombineGVCFs_chr17_job8_2550540.err
+ echo Project_Levine_January2015/CombineGVCFs/scripts/CombineGVCFs_chr17.sh
+ bash Project_Levine_January2015/CombineGVCFs/scripts/CombineGVCFs_chr17.sh
INFO  17:53:18,241 HelpFormatter - --------------------------------------------------------------------------------
INFO  17:53:18,243 HelpFormatter - The Genome Analysis Toolkit (GATK) v3.3-0-g37228af, Compiled 2014/10/24 01:07:22
INFO  17:53:18,243 HelpFormatter - Copyright (c) 2010 The Broad Institute
INFO  17:53:18,243 HelpFormatter - For support and documentation go to http://www.broadinstitute.org/gatk
INFO  17:53:18,246 HelpFormatter - Program Args: -T CombineGVCFs -R /scratch2/vyp-scratch2/reference_datasets/human_reference_sequence/human_g1k_v37.fasta -L 17 -o Project_Levine_January2015/CombineGVCFs/data/chr17.gvcf.gz --variant /cluster/project8/IBDAJE/jointgvcf/Macrogen_1/jointgvcf_chr17.vcf.gz --variant /cluster/project8/IBDAJE/jointgvcf/1410AHP-0004_ElenaSchiff_211samples/jointgvcf_chr17.vcf.gz --variant /cluster/project8/IBDAJE/jointgvcf/1411AHP-0005_ElenaSchiff_75samples/jointgvcf_chr17.vcf.gz
INFO  17:53:18,249 HelpFormatter - Executing as rmhanpo@larry-3-43.local on Linux 2.6.18-371.el5 amd64; Java HotSpot(TM) 64-Bit Server VM 1.7.0_45-b18.
INFO  17:53:18,249 HelpFormatter - Date/Time: 2015/01/06 17:53:18
INFO  17:53:18,249 HelpFormatter - --------------------------------------------------------------------------------
INFO  17:53:18,249 HelpFormatter - --------------------------------------------------------------------------------
INFO  17:53:18,718 GenomeAnalysisEngine - Strictness is SILENT
INFO  17:53:18,808 GenomeAnalysisEngine - Downsampling Settings: Method: BY_SAMPLE, Target Coverage: 1000
INFO  17:53:18,981 IntervalUtils - Processing 81195210 bp from intervals
WARN  17:53:18,982 IndexDictionaryUtils - Track variant doesn't have a sequence dictionary built in, skipping dictionary validation
WARN  17:53:18,982 IndexDictionaryUtils - Track variant2 doesn't have a sequence dictionary built in, skipping dictionary validation
WARN  17:53:18,982 IndexDictionaryUtils - Track variant3 doesn't have a sequence dictionary built in, skipping dictionary validation
INFO  17:53:19,040 GenomeAnalysisEngine - Preparing for traversal
INFO  17:53:19,042 GenomeAnalysisEngine - Done preparing for traversal
INFO  17:53:19,042 ProgressMeter - [INITIALIZATION COMPLETE; STARTING PROCESSING]
INFO  17:53:19,042 ProgressMeter -                 | processed |    time |    per 1M |           |   total | remaining
INFO  17:53:19,043 ProgressMeter -        Location |     sites | elapsed |     sites | completed | runtime |   runtime
INFO  17:53:21,027 GATKRunReport - Uploaded run statistics report to AWS S3
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A USER ERROR has occurred (version 3.3-0-g37228af):
##### ERROR
##### ERROR This means that one or more arguments or inputs in your command are incorrect.
##### ERROR The error message below tells you what is the problem.
##### ERROR
##### ERROR If the problem is an invalid argument, please check the online documentation guide
##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
##### ERROR
##### ERROR Visit our website and forum for extensive documentation and answers to
##### ERROR commonly asked questions http://www.broadinstitute.org/gatk
##### ERROR
##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
##### ERROR
##### ERROR MESSAGE: The list of input alleles must contain <NON_REF> as an allele but that is not the case at position 1869; please use the Haplotype Caller with gVCF output to generate appropriate records
##### ERROR ------------------------------------------------------------------------------------------
```
However according to
https://www.broadinstitute.org/gatk/gatkdocs/org_broadinstitute_gatk_tools_walkers_variantutils_CombineGVCFs.php
"
 they (the VCFs) must have been produced with the Haplotype Caller as part of the "single sample discovery" pipeline using the '-ERC GVCF' mode, which uses a sophisticated reference model to produce accurate genotype likelihoods for every position in the target.
"
where ERC refers to the emitRefConfidence argument I'm guessing, which is specified.

**Comment by pontikos** [comment] 2015-01-06 20:52
Ok so I don't think I can call CombineGVCFs on joint VCFs generated by HaplotypeCaller.

**Comment by vplagnol** [comment] 2015-01-07 00:28
Yes this is the point I was trying to make a few days ago. Probably not working if you want to merged already merged gVCF files. This is why I have this
msample_calling/merge_gVCF.sh
script that takes all gVCF files in a folder and makes a combined gVCF out of it, that will then be fed into genotypeGVCF.
I don't recommend doing the combinegVCF systematically for each batch, unless the batch are large-ish, at least 30 samples or so. If they are large enough, fine, combine them and put all these gVCF files into the genotyping module.

**Closed** 2015-01-07 00:28 UTC

**Comment by Baffort** [comment] 2015-09-16 09:26
hi,all.
The error also happened on my script.And Could you tell me whether to find the solution or not ?
Best Regards,
Baffort

**Comment by pontikos** [comment] 2015-09-16 09:58
Hi Baffort,

How did you generate those VCFs?  Did you use HaplotyeCaller with the
--emitRefConfidence GVCF option?

Thanks,

Nikolas.

**Comment by Baffort** [comment] 2015-09-16 10:01
DearNikolas,
Thanks for your reply. Yes, i usedHaplotyeCaller with the--emitRefConfidence GVCF option.


Best Regards,


Baffort.
Original Message
Sender:Nikolas Pontikosnotifications@github.com
Recipient:plagnollab/DNASeq_pipelineDNASeq_pipeline@noreply.github.com
Cc:Baffortzhangbaifeng1@gmail.com
Date:Wednesday, Sep 16, 2015 17:58
Subject:Re: [DNASeq_pipeline] CombineGVCFs: ERROR input alleles must containNON_REF (#14)


Hi Baffort,
 
 How did you generate those VCFs? Did you use HaplotyeCaller with the
 --emitRefConfidence GVCF option?
 
 Thanks,
 
 Nikolas.
 
 On 16 September 2015 at 10:26, Baffort notifications@github.com wrote:
  hi,all.
  The error also happened on my script.And Could you tell me whether to find
  the solution or not ?
  Best Regards,
  Baffort

**Comment by pontikos** [comment] 2015-09-16 10:41
It should work if you combine g.vcf files generated by HaplotypeCaller individually.  Our error was because the files had been combined before pass them to CombineGVCFs I think.

**Comment by Baffort** [comment] 2015-09-16 10:48
thanks all the same. My error maybe caused by unknown bug.if i have found it and you want to know, i will share it with you.


Best wishes,


Original Message
Sender:Nikolas Pontikosnotifications@github.com
Recipient:plagnollab/DNASeq_pipelineDNASeq_pipeline@noreply.github.com
Cc:Baffortzhangbaifeng1@gmail.com
Date:Wednesday, Sep 16, 2015 18:41
Subject:Re: [DNASeq_pipeline] CombineGVCFs: ERROR input alleles must containNON_REF (#14)


It should work if you combine g.vcf files generated by HaplotypeCaller individually. Our error was because the files had been combined before pass them to CombineGVCFs I think.

**Comment by rishaGovind** [comment] 2016-08-10 09:56
So how did you work around this problem?

**Comment by Baffort** [comment] 2016-08-11 08:37
I am sorry for that I can’t remember it clear. I only remember that I have posted this problem in GATK forum and then the administer advise me to process data in only one version GATK pipeline, because the format of results produced by different version GATK maybe different.


Original Message
Sender:rishaGovindnotifications@github.com
Recipient:plagnollab/DNASeq_pipelineDNASeq_pipeline@noreply.github.com
Cc:Baffortzhangbaifeng1@gmail.com; Commentcomment@noreply.github.com
Date:Wednesday, Aug 10, 2016 17:56
Subject:Re: [plagnollab/DNASeq_pipeline] CombineGVCFs: ERROR input allelesmust contain NON_REF (#14)


So how did you work around this problem?

**Comment by rishaGovind** [comment] 2016-08-12 10:09
Thanks. I was getting this error with GATK v3.2. When I tried a newer version of GATK and it worked fine.
